#define EXIT_SUCCESS 0
#define EXIT_FAILURE 1

#define FIFO_PATH "/tmp/cdoro_daemon"

#define POMODORO_START 1
#define POMODORO_STOP 2
#define POMODORO_BREAK 3

#define CDORO_DAEMON_NULL_ARG -1

#define CDORO_DAEMON_DISCONNECTED -1
#define CDORO_DAEMON_ALREADY_START -2
#define CDORO_DAEMON_ALREADY_BREAK -3
#define CDORO_DAEMON_ALREADY_STOP -4
#define CDORO_DAEMON_ALREADY_RUNNING -5

#define CDORO_DAEMON_SUCCESS 0
